### ISSUE TITLE
one-hot-palette-label in 2_F versus 1_FRLR

### ISSUE THREAD

**Issue by chen-harrison** [ika-rwth-aachen/Cam2BEV#10]
Thanks so much for sharing this method and code in such a well-documented fashion. I just had a question of clarification regarding the use of different one-hot-palette labels in the mutli-view versus single-view networks.

I started off training the 1_FRLR method, and I observe that the one-hot-palette-input, convert_10, and the one-hot-palette-label, convert_9+occl, seem very similar - the main difference is that the "sky" RGB values are changed to "occluded" instead, which makes sense because the inputs will not see an occluded class, and the BEV will not see the sky.

However, now looking at the 2_F config file, I see that while convert_10 is still used for the one-hot-palette-input, the one-hot-palette-label is now using convert_3+occl. My understanding is that now the network input views are seeing classes that the ground truth input will never have - for example, terrain that was seen as "9" in the input will be understood as "3" in the ground truth BEV. So my questions are:

1. What was the rationale of reducing the label classes? Is it because less camera views mean 4 times less data, and having too many classes doesn't allow adequate training on all of them?
2. If my understanding of the input to label process is correct, does the network eventually just learn to convert those terrain areas, oroginally understood as "9", to "3" to match the ground truth?

**Comment by lreiher** [comment]
Sorry for the late reply.

More classes in the input mean more information for the network to work with. Fewer classes in the output potentially present an easier task (e.g. predicting only road, cars, obstacles seems simpler than predicting many more classes).

The rationale for using `convert_3+occl` with the `2_F` dataset (potentially easing the task) was its usage for testing the real-world application of the approach, see the section in our paper.

Feel free to try out the `2_F` dataset with other one-hot-palettes!
