### ISSUE TITLE
How can I simulate the data myself ?

### ISSUE THREAD

**Issue by CoderChen01** [ika-rwth-aachen/Cam2BEV#12]
Thank you very much for your excellent work. I would like to ask how I can download VTD ?

**Comment by bastilam** [comment]
Virtual Test Drive (VTD) is a commercial product. You may find additional information here: https://www.mscsoftware.com/product/virtual-test-drive.

**Comment by CoderChen01** [comment]
I have seen this, but I did not find the student version, is it not provided?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bastian ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ika-rwth-aachen/Cam2BEV] How can I simulate the data myself ? (#12)





 
Virtual Test Drive (VTD) is a commercial product. You may find additional information here: https://www.mscsoftware.com/product/virtual-test-drive.

**Comment by bastilam** [comment]
I do not know whether they provide a student version. You would have to contact the vendor and ask.

**Comment by CoderChen01** [comment]
Ok, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bastian ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 下午3:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ika-rwth-aachen/Cam2BEV] How can I simulate the data myself ? (#12)





 
I do not know whether they provide a student version. You would have to contact the vendor and ask.
