### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by Northengard** [ika-rwth-aachen/Cam2BEV#17]
Hello,
Thanks for sharing your work, it looks awesome. Would you be pleased to provide pretrained weights of your models? It would be much easier to compare custom results with your work if there is no need to reproduce training, that may takes a lot of time unfortunately. 

Best regards.

**Comment by Northengard** [comment]
I've seen https://github.com/ika-rwth-aachen/Cam2BEV/issues/8 but may be there is a chance that your policy has changed  😊

**Comment by bastilam** [comment]
Dear @Northengard, our policy did not change. All algorithms and data to reproduce the models from our paper are available.
