### ISSUE TITLE
A Recommendation on Modifying the Resolution of Example Images in Your Dataset

### ISSUE THREAD

**Issue by johannwyh** [ika-rwth-aachen/Cam2BEV#2]
First and foremost, thank you for providing such a brilliant work!
Now here comes my issue. I firstly download the synthetic dataset you provide. Then when I try to use the `ipm.py` in your pre-processing directory, I use the front/rear/left/right images in the **data/1\_FRLR/examples**, and the camera calibration files in **preprocessing/camera\_configs/1_FRLR/**, as the argument. This results in **a totally blank image output**.
After a debug through your code, I realize that it is caused by the non-matched resolution of images in example directory. Your configuration files tell that your cameras have a resolution of `964x604`, while the example images have a resolution of `320x200`. 
Now I understand that this directory is used to store the images used to be shown in your README and I should select a set of images in **train** or **val** directory. **However, for anyone coming up with this repo for the first time, such arrangement is _very very very confusing_.** Cause at that moment we can hardly understand that it is a repo in your GitLab.
Therefore I highly recommend that you adjust such arrangement, maybe give images in examples directory proper resolution, or put another example images in your preprocessing directory.
It is not a critical issue. Your work is still generally wonderful!

**Comment by lreiher** [comment]
Thanks for your feedback and recommendation! You are right, the purpose of the `examples` folder is not directly visible to users who simply use the provided `download.sh`. I just replaced the example images with ones from the dataset, keeping them at the same resolution.

**Comment by johannwyh** [comment]
Wow, really fast response! Thank you very much!
