### ISSUE TITLE
Training of deeplab-mobilenet and deeplab-xception failed

### ISSUE THREAD

**Issue by LimJiaJing** [ika-rwth-aachen/Cam2BEV#22]
I tried reproducing the results mentioned in the paper. To train deeplab-xception and deeplab-mobilenet, I simply changed "./train.py -c config.1_FRLR.unetxst.yml" to "./train.py -c config.1_FRLR.deeplab-xception.yml" and "./train.py -c config.1_FRLR.deeplab-mobilenet.yml". The training successfully starts but no improvement in performance occurs. I did not change any of the configurations and the training stops at epoch 21 for both models. Thanks for your time and I look forward to your guidance.

**Comment by lreiher** [comment]
Have you worked with the most recent version of the repository?

Just this week I merged [this PR](https://github.com/ika-rwth-aachen/Cam2BEV/pull/20), downgrading from TensorFlow 2.7 to 2.5.

Re-creating your Python environment with the most recent requirements.txt should resolve your issue. Please let us know if it does.

**Comment by LimJiaJing** [comment]
Yes, it has solved the problem. Thank you!
