### ISSUE TITLE
What changes to make to resume training from where it was left off?

### ISSUE THREAD

**Issue by KishanKartha** [ika-rwth-aachen/Cam2BEV#23]
Hi, I cannot do the whole training in one go, thus I have to do multiple training sessions. I couldn't figure a way to resume training from where it was left off during the last training session, like loading the last trained weights and then doing the training. 
Thank you for your time. looking forward to your reply.

**Comment by lreiher** [comment]
You can run `./train.py --help` to get an overview of all accepted parameters of the training script.

There you will also find `--model-weights`, which you can point to an existing checkpoints weights file (`.hdf5` I think) from a previous run's output folder.

**Comment by KishanKartha** [comment]
thank you for the reply.
