### ISSUE TITLE
some issue about "homography_converter"

### ISSUE THREAD

**Issue by yyyzwy** [ika-rwth-aachen/Cam2BEV#31]
Hello, thank you for this repository and the ideas. I'm trying to reproduce this work recently. 
I find the performace on my dataset of using **SpatialTransformer to preprocess the input images** is not better than **splice the IPM images together**, so i am trying to find where i did wrong about the SpatialTransformer unit.

In order to use the uNetXST model, I need to pre calculate **uNetXST_ homographies** for 1_ FRLR.py as `theta_ init`, the init parameter input into the SpatialTransformer, but I found that the **uNetXST_ homographies** i calculated by provided script related to the **front camera** cannot match the data provided in `preprocessing/holography provided in the code_ converter/uNetXST_ homographies/1_ FRLR.py`, but the other three cameras I calculated are all matched.
```python
# uNetXST_ homographies about front
# provided in 1_FRLR.py
  np.array([[4.651574574230558e-14, 10.192351107009959, -5.36318723862984e-07],
            [-5.588661045867985e-07, 0.0, 2.3708767903941617],
            [35.30731833118676, 0.0, -1.7000018578614013]]),     # front

# what i calculated:
# use the ipm_homographs provide by preprocessing/homography_converter/README.md
[[6.5627512483814406e-15, 10.192351107009959, -5.363187232807152e-07], 
[-5.588661045867985e-07, 0.0, 2.3708767903941617], 
[35.30731833118676, 0.0, -1.7000018578614013]]
````

For this reason, I recalculated the **homographs of IPM**, and found that the parameters of **cameras** are also not the same as what provided in `preprocessing/homography_converter/README.md`.
````python
# what provided in preprocessing/homography_converter/README.md
# OpenCV homography for front:
# [[0.0, 0.8841865353311344, -253.37277367000263], [0.049056392233805146, 0.5285437237795494, -183.265385638118], [-0.0, 0.001750144780726984, -0.5285437237795492]]
# OpenCV homography for rear:
# [[6.288911300436434e-18, 0.8292344604207404, -264.08036704706365], [-0.04905639223380515, 0.5285437237795513, -135.9750235247304], [-0.0, 0.0017501447807269904, -0.5285437237795512]] 
# OpenCV homography for left:
# [[0.04905639223380514, 0.7984814950483465, -264.7865925612947], [3.0038376863423275e-18, 0.4821577791689496, -159.26320930902278], [-0.0, 0.0016334684620118568, -0.49330747552758086]] 
# OpenCV homography for right:
# [[-0.04905639223380516, 0.7984814950483448, -217.49623044790604], [3.0038376863423283e-18, 0.5044571718862112, -138.69450590963578], [-0.0, 0.0016334684620118542, -0.49330747552758]] 

# what i calculated:
OpenCV homography for front:
[[6.288911300436432e-18, 0.8841865353311336, -253.37277367000237], [0.049056392233805146, 0.5285437237795487, -183.26538563811778], [1.1577177764518928e-20, 0.0017501447807269821, -0.5285437237795486]]
OpenCV homography for rear:
[[6.288911300436434e-18, 0.8292344604207396, -264.08036704706336], [-0.049056392233805146, 0.5285437237795507, -135.97502352473026], [-4.194994772127064e-21, 0.0017501447807269886, -0.5285437237795506]]
OpenCV homography for left:
[[0.04905639223380514, 0.7984814950483464, -264.7865925612947], [3.0038376863423302e-18, 0.48215777916894953, -159.26320930902278], [8.805125002324379e-36, 0.0016334684620118568, -0.49330747552758086]]
OpenCV homography for right:
[[-0.04905639223380516, 0.7984814950483449, -217.49623044790607], [3.0038376863423263e-18, 0.5044571718862112, -138.69450590963578], [-5.442256126106322e-36, 0.0016334684620118542, -0.49330747552758]]
````
which leads to more differences in the result of **uNetXST_ homographies**, but surprisingly the result about **right camera** is same as the file provided:
```python
H = [
    np.array([[4.651574574230558e-14, 10.192351107009959, -5.36318723862984e-07],
              [-5.588661045867985e-07, 0.0, 2.3708767903941617],
              [35.30731833118676, 0.0, -1.7000018578614013]]),  # front
    # what i calculated
    # [[-5.336674296656391e-14, 10.192351107009959, -5.363187163709389e-07],
    # [-5.588660999399972e-07, -1.3484445368213003e-16, 2.3708767903941643],
    # [35.30731833118661, -1.5835212325065431e-16, -1.700001857861401]]

    np.array([[-5.336674306912119e-14, -10.192351107009957, 5.363187220578325e-07],
              [5.588660952931949e-07, 3.582264351370481e-23, 2.370876772982613],
              [-35.30731833118661, -2.263156574813233e-15, -0.5999981421386035]]),  # rear
    # what i calculated
    # [[2.6539246969884692e-14, -10.192351107009959, 5.363187207328902e-07],
    # [5.58866099939995e-07, -4.8860892910808006e-17, 2.3708767729826152],
    # [-35.30731833118661, -2.9784330148858767e-15, -0.5999981421386087]]

    np.array([[20.38470221401992, 7.562206982469407e-14, -0.28867638384075833],
              [-3.422067857504854e-23, 2.794330463189411e-07, 2.540225111648729],
              [2.1619497190382224e-15, -17.65365916559334, -0.4999990710692976]]),  # left
    # what i calculated
    # [[20.38470221401992, 3.566907532807007e-14, -0.28867638384075667],
    # [-3.422067879481381e-23, 2.794330463189408e-07, 2.5402251116487293],
    # [2.1619497190382196e-15, -17.65365916559332, -0.4999990710692995]]

    np.array([[-20.38470221401991, -4.849709834037436e-15, 0.2886763838407495],
              [-3.4220679184765114e-23, -2.794330512976549e-07, 2.5402251116487626],
              [2.161949719038217e-15, 17.653659165593304, -0.5000009289306967]])  # right
    # what i calculated
    # [[-20.38470221401991, -4.849709834037436e-15, 0.28867638384074945],
    # [-3.4220679184765114e-23, -2.794330512976549e-07, 2.5402251116487626],
    # [2.161949719038217e-15, 17.653659165593304, -0.5000009289306967]]
]
```
The difference seems small due to the order of magnitude, but I'm not sure whether it will affect the performance of the uNetXST model, because the performance of the uNetXST model on my dataset is not as good as the result obtained by directly using the IPM image as input.

**Finally, Is my calculation correct? if I want to use my own dataset, how can I get the correct uNetXST_Homographs value?**

**Comment by lreiher** [comment]
Do I correctly understand that all differences you are spotting in the computations are on the order of 1e-14 and smaller? In that case, I wouldn't worry about it, probably just floating point computation issues on that scale, which might also vary between different computers.

If currently you are only trying to reproduce the results, may I ask what MIoU values you are achieving on the provided datasets? I'm assuming that you didn't change any config files?

> if I want to use my own dataset, how can I get the correct uNetXST_Homographs value?

1. Create new camera configuration files [like the ones here](https://github.com/ika-rwth-aachen/Cam2BEV/tree/master/preprocessing/camera_configs/1_FRLR), containing the intrinsic/extrinsic parameters of your own camera setup.
2. Run [preprocessing/occlusion/occlusion.py](https://github.com/ika-rwth-aachen/Cam2BEV/blob/master/preprocessing/occlusion/occlusion.py)
3. Run [preprocessing/occlusion/ipm.py](https://github.com/ika-rwth-aachen/Cam2BEV/blob/master/preprocessing/occlusion/ipm.py) with your own camera config files
4. Compute uNetXST-compatible homographies with your own camera config files by following the instructions in [preprocessing/homography_converter](https://github.com/ika-rwth-aachen/Cam2BEV/blob/master/preprocessing/homography_converter
5. Adjust or create a new one-hot conversion file ([model/one_hot_conversion](https://github.com/ika-rwth-aachen/Cam2BEV/blob/master/model/one_hot_conversion))
6. Set all training parameters in a dedicated config file
7. Start training

**Comment by yyyzwy** [comment]
> Do I correctly understand that all differences you are spotting in the computations are on the order of 1e-14 and smaller?

Yes, that's right. So maybe i don't need to worry it anymore.

> If currently you are only trying to reproduce the results, may I ask what MIoU values you are achieving on the provided datasets? I'm assuming that you didn't change any config files?

Actually i am using my own dataset,  and expect the the model will act just fine like it on provided dataset. But consider the difference between the dataset, this maybe be unreasonable.

I checked the images that warpped by the `IPM_homographs` i calculated, it seems right and make sense, so i think that the calculation of `IPM_homographs` about my camera settings is right. So the `uNetXST_ homographies` that i calculated should also be right, because it is simplely obtained by inputting `IPM_homographs` parameters into the conversion script. 

And the **MIoU of uNetXST on my dataset** is about **63%**, if i use the **IPM image as input, send to Deeplab MobileNetV2** model, the MIoU i got is about **66%**.

**Comment by lreiher** [comment]
It seems too coincidental that your own camera images would transform just fine with our dataset's camera intrinsics and extrinsics. Would you mind sharing your input images and transformed IPM images?

**Comment by yyyzwy** [comment]
No, I didn't use your camera parameters. I recalculated it for my camera settings. But the effect did not meet the expectation, so I thought it was because I had miscalculated the relevant homographs parameters.

> Drone
![image](https://user-images.githubusercontent.com/114383472/192678039-83833636-9d35-443a-8c6b-0ffb7f8e4760.png)

> IPM
![image](https://user-images.githubusercontent.com/114383472/192675096-b17386e9-22dc-4828-99d4-aabaef44b6b6.png)

> front
![image](https://user-images.githubusercontent.com/114383472/192678681-554224a6-69c7-40ef-b00c-e18e5e043912.png)

> rear
![image](https://user-images.githubusercontent.com/114383472/192678430-1de483b8-84a4-4907-a197-ecc47c61202e.png)

> left
![image](https://user-images.githubusercontent.com/114383472/192678479-5f408509-f5e5-44df-94a7-245a846cc490.png)

> right
![image](https://user-images.githubusercontent.com/114383472/192678395-cf80692f-c322-4238-9eea-34bf90c303e3.png)

**Comment by lreiher** [comment]
Ah okay, got it. Your IPM image looks correct. If you have then converted the homographies printed by the IPM-script using the homography converter, you have correctly followed the steps.

Did you also apply the occlusion script to the drone label image?

**Comment by yyyzwy** [comment]
Yep.
![image](https://user-images.githubusercontent.com/114383472/192925514-05e66821-2285-47ba-bb37-1e9d8c7e0ea7.png)

**Comment by lreiher** [comment]
Okay, this is also looking good. Another thing to check might be your color palette, i.e., which color represents which class and which classes are merged before presenting input to the network.

Could you also show some predictions given by uNetXST or DL MobileNet?

**Comment by yyyzwy** [comment]
Here is a example.
![image](https://user-images.githubusercontent.com/114383472/194200473-a37efeaf-0c33-4117-aa2a-e43933093627.png)

The difference between input color palette and output color palette is the "Occluded" I added in the output color palette.
And if there is problem with the color palette, all model should be affected, I think...

**Comment by yyyzwy** [comment]
This is the same result predict by uNetXST.
![image](https://user-images.githubusercontent.com/114383472/194211236-0cfb9d38-3c71-4973-acb4-669c734ec936.png)

**Comment by lreiher** [comment]
I believe we cannot guarantee that uNetXST would always outperform the other models. I can only give one further suggestion right now what you could investigate: debugging the uNetXST model, you could take a look at the feature maps before and after the Spatial Transformer modules inside the network to check that the IPM transformation is working as expected inside the network.
