### ISSUE TITLE
drone camera config file

### ISSUE THREAD

**Issue by grdiv** [ika-rwth-aachen/Cam2BEV#33]
Hello!I would like to ask whether drone config parameter is specified the exact value or we can choose an suitable one? if specified the exact value,how it was obtained

**Comment by lreiher** [comment]
Do you mean the file [`drone.yaml`](preprocessing/camera_configs/1_FRLR/drone.yaml)?

The configuration corresponds to the (virtual) drone that was used to record ground-truth labels for the dataset 1_FRLR. If you train a network on that dataset, it will output a prediction matching the field of view of the ground-truth labels. Once trained, you cannot change this field of view.

You could, however, generate a new dataset with a different drone configuration. That's what we did with dataset 2_F as well.

**Comment by grdiv** [comment]
> 

I see. Thank you
