### ISSUE TITLE
Real-world application

### ISSUE THREAD

**Issue by TBauer2000** [ika-rwth-aachen/Cam2BEV#37]
Hi,

I am planning to use your software for a real application. I want to use the single input model with the uNetXST configuration and a single front facing camera. Is there any way to train the model with your dataset or do I need to create my own dataset with my camera parameters? Also, my camera operates in HD resolution (1280x720), does the training data also need to have the same resolution?

Many thanks in advance!

**Comment by lreiher** [comment]
The intrinsic and extrinsic camera calibration is a hyperparameter to the network, see the very bottom of the README.

Training on one camera configuration and dataset, but then inferencing on another camera configuration will most likely worsen performance.

It would therefore be suggested to train on a custom dataset with your own camera configuration. This also allows you to choose a more suitable resolution.
