### ISSUE TITLE
field of view single-input model

### ISSUE THREAD

**Issue by meissnerda71974** [ika-rwth-aachen/Cam2BEV#38]
First of all thank you so much for this great work.

In the paper I read that the field of view of the ground truth image for the full 360° is approximately 70m x 44m. Do you have an approximation of the field of view of the single-input model too? 
Based on the ground truth BEV image it might also let us do an approximation of which field of view it might have on a real world application? 

Thanks a lot in advance.

**Comment by lreiher** [comment]
Some trigonometry gives us a very simple equation:

fov_m = z_drone * f / res

Here, fov_m is the field of view in meters, z_drone the height of the virtual drone camera, f its focal length and res its resolution.

All values can be found [here](https://gitlab.ika.rwth-aachen.de/cam2bev/cam2bev-data/-/tree/master/2_F).

This yields an FoV of 50m x 25m.

**Comment by meissnerda71974** [comment]
Great, thanks a lot!
