### ISSUE TITLE
the R matrix calculate order may have some problem?

### ISSUE THREAD

**Issue by lucky-sinx** [ika-rwth-aachen/Cam2BEV#39]
halo, in ipm.py when set the R matrix for Camera, the apply order is first pitch, then apply yaw:
![image](https://github.com/ika-rwth-aachen/Cam2BEV/assets/55487149/b73a820f-deea-4c26-b0c5-2b830c9aa8f5)
this may cause apply yaw is not right because the Y axis is changed after we apply pitch?
(although its ok when pitch is 0.when i changed the pitch t0 no-zero, it generate wrong answer)
i think we should first apply yaw, and then apply pitch.
![image](https://github.com/ika-rwth-aachen/Cam2BEV/assets/55487149/65f6907b-3c78-4fc0-9e6d-da835c150547)

**Comment by lreiher** [comment]
You may be right and may need to switch the axes order. Feel free to change it in your own fork. Unfortunately, I currently do not have the time to check and we are not planning to update this repository anytime soon anyway. You should be able to easily tell from the IPM output whether your correction is right or not.
