### ISSUE TITLE
The preprocessing issue

### ISSUE THREAD

**Issue by ElaheDlv** [ika-rwth-aachen/Cam2BEV#42]
Hi,
I have a problem doing the occlussion preprocessing as the ego vehicle also gets the castray different from the one that is in the downloaded preprocessed image. Can you tell me what makes it different?
![t_0_0_0001000](https://github.com/user-attachments/assets/b02d1541-1203-4cd8-8846-605c6cc4c25d)
![t_0_0_0001000](https://github.com/user-attachments/assets/dd47259d-c003-4729-ab87-27101a9122bd)

**Comment by lreiher** [comment]
Hard to tell what is wrong without exactly knowing what command you are running on what data.

**Comment by ElaheDlv** [comment]
@lreiher Sorry I forgot to mention that, I used this command as you mentioned in you repo ./occlusion.py \
    --batch ../../data/1_FRLR/train/bev \
    --output ../../data/1_FRLR/train/bev+occlusion \
    ../camera_configs/1_FRLR/drone.yaml \
    ../camera_configs/1_FRLR/front.yaml \
    ../camera_configs/1_FRLR/rear.yaml \
    ../camera_configs/1_FRLR/left.yaml \
    ../camera_configs/1_FRLR/right.yaml
for your own dataset but as you can see, the castrays are not right. Seems like the vehicle is not considered as ego vehicle.

**Comment by ElaheDlv** [comment]
I am using the same yaml file as is in this repo. I double checked it. Can you help me understand what exactly is needed to be modified in the yaml file to work on the dataset you have provided?
