### ISSUE TITLE
Co-ordinate system convention

### ISSUE THREAD

**Issue by ektas0330** [ika-rwth-aachen/Cam2BEV#9]
Hello,

Thank you for sharing such a well-documented code repository for your work! Could you also share the co-ordinate system (left-handed, right-handed, or something else) that the` preprocessing/ipm/ipm.py `code is following. I see a comment about switching axes in the `setR()` function so just wanted to make sure.

Thanks!

**Comment by lreiher** [comment]
It's been a while and I only spent a couple minutes thinking about it before writing this comment, but hope this helps ;)
- world frame is matched to vehicle frame, i.e. right-handed coordinate system with x pointing in the direction of forward driving, y pointing to the left of the car, z pointing upwards
- image frame is 2-dimensional, with x pointing to the right (image width) and y pointing downwards (image height), so origin is at image's top left corner
- hence the comment `# switch axes (x = -y, y = -z, z = x)`: x in image plane is negative y in world frame, and so on ...
- possible rotations of the camera are taken into account by the rotation matrices in `setR()`

**Comment by ektas0330** [comment]
Thank you for the response. It answers my questions!
